# Site settings
title: VCA

exclude:
  - app.js
  - settings.js
  - views/
  - "*.db"
  - node_modules
  - package.json
  - gulpfile.js
  - .gitignore
  - README.md

# locale settings
default_locale:     "en"
authorized_locales: ["en","es"]
